version: '3'
#volumes:
#  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - db
  db:
    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
